#!/usr/bin/env bash
# GENERATED by scripts/build-plugins.mjs — do not edit; edit the pack sources and re-run.
# PostToolUse Edit|Write|MultiEdit (plugin mode): run this pack's hooks/post-edit-reminders.*.sh
# with the edited path and return any reminder as additionalContext (plain PostToolUse stdout
# never reaches the model). Fail-open.
root="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
file="$(node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const t=JSON.parse(s).tool_input||{};process.stdout.write(t.file_path||t.path||"")}catch{}})' 2>/dev/null)"
[ -n "$file" ] || exit 0
msg=""
for h in "$root"/hooks/post-edit-reminders.*.sh; do
  [ -f "$h" ] || continue
  r="$(bash "$h" "$file" 2>/dev/null || true)"
  [ -n "$r" ] && msg="${msg:+$msg
}$r"
done
[ -n "$msg" ] || exit 0
node -e 'process.stdout.write(JSON.stringify({hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:process.argv[1]}}))' "$msg" 2>/dev/null || printf '%s\n' "$msg"
exit 0
