#!/usr/bin/env bash
# GENERATED by scripts/build-plugins.mjs — do not edit; edit the pack sources and re-run.
# SessionStart (plugin mode): inject this stack pack's CLAUDE.md fragment. Fail-open.
f="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}/claude.fragment.md"
[ -f "$f" ] || exit 0
node -e 'const fs=require("fs");process.stdout.write(JSON.stringify({hookSpecificOutput:{hookEventName:"SessionStart",additionalContext:fs.readFileSync(process.argv[1],"utf8")}}))' "$f" 2>/dev/null || cat "$f"
exit 0
