#!/usr/bin/env node
// build-plugins.mjs — generate the Claude Code plugin distribution of engsys.
//
// engsys ships two ways from the same sources:
//   * copy mode   — `engsys install` materializes files into a project's .claude/ (unchanged)
//   * plugin mode — a Claude Code marketplace: the `engsys` core plugin + one `engsys-<value>`
//                   plugin per stack pack, enabled per project and pinned by git ref.
//
// Everything this script writes lives under a `.claude-plugin/` directory (plus a pack-root
// `.mcp.json` where the pack declares MCP servers) — paths the copy-mode installer never
// copies — so plugin mode cannot change a copy-mode install. Components (agents/, commands/, skills/) are auto-discovered from each plugin root; this script only adds
// manifests, hook wiring, and small generated hook scripts derived from each pack's own sources
// (claude.fragment.md, settings.fragment.json mcpServers, hooks/post-edit-reminders.*.sh).
//
// Usage: node scripts/build-plugins.mjs          # (re)generate
//        node scripts/build-plugins.mjs --check  # exit 1 if generated files are stale (CI)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const pkg = JSON.parse(fs.readFileSync(path.join(REPO, 'package.json'), 'utf8'));
const VERSION = pkg.version;
const SCHEMA = 'https://anthropic.com/claude-code/plugin.schema.json';
const AUTHOR = { name: 'eric-sabe' };
const HOMEPAGE = 'https://github.com/eric-sabe/engsys';
// Worker-provider packs only render copy-mode worker config (.claude/scripts/providers.json);
// they have no plugin-mode meaning yet.
const PLUGIN_EXCLUDE = (cat, val) => cat === 'tooling' && val.startsWith('provider-');

const GEN = '# GENERATED by scripts/build-plugins.mjs — do not edit; edit the pack sources and re-run.';
const json = (o) => JSON.stringify(o, null, 2) + '\n';
const out = new Map(); // relPath -> content

const packContextSh = `#!/usr/bin/env bash
${GEN}
# SessionStart (plugin mode): inject this stack pack's CLAUDE.md fragment. Fail-open.
f="\${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}/claude.fragment.md"
[ -f "$f" ] || exit 0
node -e 'const fs=require("fs");process.stdout.write(JSON.stringify({hookSpecificOutput:{hookEventName:"SessionStart",additionalContext:fs.readFileSync(process.argv[1],"utf8")}}))' "$f" 2>/dev/null || cat "$f"
exit 0
`;

const packPostEditSh = `#!/usr/bin/env bash
${GEN}
# PostToolUse Edit|Write|MultiEdit (plugin mode): run this pack's hooks/post-edit-reminders.*.sh
# with the edited path and return any reminder as additionalContext (plain PostToolUse stdout
# never reaches the model). Fail-open.
root="\${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
file="$(node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const t=JSON.parse(s).tool_input||{};process.stdout.write(t.file_path||t.path||"")}catch{}})' 2>/dev/null)"
[ -n "$file" ] || exit 0
msg=""
for h in "$root"/hooks/post-edit-reminders.*.sh; do
  [ -f "$h" ] || continue
  r="$(bash "$h" "$file" 2>/dev/null || true)"
  [ -n "$r" ] && msg="\${msg:+$msg
}$r"
done
[ -n "$msg" ] || exit 0
node -e 'process.stdout.write(JSON.stringify({hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:process.argv[1]}}))' "$msg" 2>/dev/null || printf '%s\\n' "$msg"
exit 0
`;

// ---- core plugin -------------------------------------------------------------
out.set('core/.claude-plugin/plugin.json', json({
  $schema: SCHEMA,
  name: 'engsys',
  version: VERSION,
  description: 'engsys core — a stack-agnostic engineering team for Claude Code: personas, merge/maintenance orchestrators with subagent liveness, dev commands, and workflows. Pair with engsys-<stack> pack plugins.',
  author: AUTHOR,
  homepage: HOMEPAGE,
  license: 'MIT',
  hooks: './.claude-plugin/hooks.json',
}));
out.set('core/.claude-plugin/hooks.json', json({
  hooks: {
    // Auto-approve engsys's own bookkeeping scripts when invoked as a single literal-path command
    // (their plugin-cache path can't be pre-approved by a portable permission rule).
    PreToolUse: [
      { matcher: 'Bash', hooks: [{ type: 'command', command: 'node "${CLAUDE_PLUGIN_ROOT}/.claude-plugin/approve-own-scripts.mjs"' }] },
    ],
    SessionStart: [
      { hooks: [{ type: 'command', command: 'node "${CLAUDE_PLUGIN_ROOT}/.claude-plugin/engsys-context.mjs"' }] },
      { matcher: 'compact', hooks: [{ type: 'command', command: 'bash "${CLAUDE_PLUGIN_ROOT}/templates/post-compact-reground.sh.tmpl"' }] },
      { matcher: 'clear|resume', hooks: [{ type: 'command', command: 'bash "${CLAUDE_PLUGIN_ROOT}/templates/post-clear-reground.sh.tmpl"' }] },
    ],
  },
}));

// ---- stack-pack plugins --------------------------------------------------------
const marketplacePlugins = [{
  name: 'engsys',
  source: './core',
  description: 'engsys core: personas, orchestrators, commands, workflows (stack-agnostic).',
}];

const stacksDir = path.join(REPO, 'stacks');
for (const cat of fs.readdirSync(stacksDir).sort()) {
  const catDir = path.join(stacksDir, cat);
  if (!fs.statSync(catDir).isDirectory()) continue;
  for (const val of fs.readdirSync(catDir).sort()) {
    const dir = path.join(catDir, val);
    if (!fs.statSync(dir).isDirectory() || PLUGIN_EXCLUDE(cat, val)) continue;
    const rel = path.relative(REPO, dir);
    const name = `engsys-${val}`;

    let mcpServers;
    const sfrag = path.join(dir, 'settings.fragment.json');
    if (fs.existsSync(sfrag)) {
      const s = JSON.parse(fs.readFileSync(sfrag, 'utf8'));
      if (s.mcpServers && Object.keys(s.mcpServers).length) mcpServers = s.mcpServers;
    }
    const hasFragment = fs.existsSync(path.join(dir, 'claude.fragment.md'));
    const hooksDir = path.join(dir, 'hooks');
    const hasReminders = fs.existsSync(hooksDir)
      && fs.readdirSync(hooksDir).some((f) => /^post-edit-reminders\..+\.sh$/.test(f));

    const hooks = {};
    if (hasFragment) {
      hooks.SessionStart = [{ hooks: [{ type: 'command', command: 'bash "${CLAUDE_PLUGIN_ROOT}/.claude-plugin/context.sh"' }] }];
      out.set(`${rel}/.claude-plugin/context.sh`, packContextSh);
    }
    if (hasReminders) {
      hooks.PostToolUse = [{ matcher: 'Edit|Write|MultiEdit', hooks: [{ type: 'command', command: 'bash "${CLAUDE_PLUGIN_ROOT}/.claude-plugin/post-edit.sh"' }] }];
      out.set(`${rel}/.claude-plugin/post-edit.sh`, packPostEditSh);
    }
    if (Object.keys(hooks).length) out.set(`${rel}/.claude-plugin/hooks.json`, json({ hooks }));

    const description = `engsys stack pack — ${cat}: ${val}. Adds ${val}-specific skills${hasFragment ? ' and guidance' : ''}${mcpServers ? ' and MCP servers' : ''} to the engsys core plugin.`;
    out.set(`${rel}/.claude-plugin/plugin.json`, json({
      $schema: SCHEMA,
      name,
      version: VERSION,
      description,
      author: AUTHOR,
      homepage: HOMEPAGE,
      license: 'MIT',
      ...(Object.keys(hooks).length ? { hooks: './.claude-plugin/hooks.json' } : {}),
    }));
    // MCP servers: plugin-root .mcp.json (inline/path `mcpServers` in plugin.json validate but are not
    // registered by Claude Code). The copy-mode installer reads settings.fragment.json and never copies it.
    if (mcpServers) out.set(`${rel}/.mcp.json`, json({ mcpServers }));
    marketplacePlugins.push({ name, source: `./${rel}`, description: `engsys ${cat} pack: ${val}` });
  }
}

out.set('.claude-plugin/marketplace.json', json({
  name: 'engsys',
  owner: AUTHOR,
  metadata: {
    description: 'engsys — an AI engineering team for any Claude Code project, as plugins: the stack-agnostic core plus one plugin per stack pack.',
    version: VERSION,
  },
  plugins: marketplacePlugins,
}));

// ---- write / check ---------------------------------------------------------------
let stale = 0;
for (const [rel, content] of out) {
  const abs = path.join(REPO, rel);
  const cur = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (cur === content) continue;
  if (CHECK) { console.error(`stale: ${rel}`); stale++; continue; }
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content, { mode: rel.endsWith('.sh') ? 0o755 : 0o644 });
  console.log(`wrote ${rel}`);
}
if (CHECK) {
  if (stale) { console.error(`build-plugins: ${stale} generated file(s) stale — run: node scripts/build-plugins.mjs`); process.exit(1); }
  console.log(`build-plugins: OK — ${out.size} generated files current (${marketplacePlugins.length} plugins, v${VERSION})`);
} else {
  console.log(`build-plugins: ${marketplacePlugins.length} plugins, v${VERSION}`);
}
