#!/usr/bin/env node
// worker-run.mjs — dispatch ONE worker run under the engsys worker contract.
//
// docs/multi-provider-spec.md § 3. The conductor (Claude session) builds a work
// package with worker-package.mjs, then calls this runner. The runner validates
// the package, spawns the provider adapter, and validates the protocol footer.
// It never runs gates as the merge authority and never commits — the conductor
// owns both.
//
// Usage:
//   node .claude/scripts/worker-run.mjs --package tmp/worker-package/<run-id> \
//        [--provider <name>] [--model <id>] [--effort <level>] [--force-provider]
//   node .claude/scripts/worker-run.mjs --check --provider <name>
//
// Exit contract — one grammar for every role (spec § 3.2):
//   0  protocol complete + positive outcome (STATUS: IMPLEMENTED/COMPLETE, VERDICT: CLEAN)
//   1  protocol complete + negative outcome (VERDICT: FINDINGS, STATUS: REFUSED/BLOCKED)
//      — a refusal with premise evidence is a SUCCESSFUL communication, not a failure
//   2  did not run, could not be attributed, or protocol violated (no receipt,
//      malformed footer, tree drift, missing binary, package tamper)
//   A caller must never read 2 as 1, and must never read either as a pass.
//
// The guards in this file are lifted from campos27's codex-review.mjs, where
// every one of them is annotated with the false green that motivated it. The
// annotations travel with the code — they are the reason the code is shaped
// this way, and deleting them invites re-learning each lesson at review cost.

import { execFileSync, spawnSync } from 'node:child_process';
import { appendFileSync, existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const SCRIPT_DIR = import.meta.dirname;
const args = process.argv.slice(2);

/** Exit 2 == "did not run / protocol violated". EVERY failure routes here,
 *  including argument and setup errors. An earlier campos27 cut let those exit
 *  1, which the contract defines as "ran, found things" — so a typo'd flag
 *  routed phantom findings to the implementer instead of invoking the fallback. */
function unavailable(what, remedy) {
	console.error(`\nworker-run: DID NOT RUN — ${what}`);
	console.error(`worker-run: ${remedy}`);
	console.error(
		'worker-run: this is NOT a completed run. Fall back to the next provider in the\n' +
			'            review_fallback_chain (minus the author family) — the work still\n' +
			'            needs its gate before anything merges.',
	);
	process.exit(2);
}

process.on('uncaughtException', (err) => {
	unavailable(`unexpected error: ${err?.stack || err}`, 'This is a bug in worker-run.mjs.');
});

// A value-taking flag in the LAST argv slot must not fall back silently — in
// campos27 a dropped `--brief` value ran the default correctness brief and
// exited 0: an intended design pass silently counted as the correctness gate.
const flag = (name) => args.includes(`--${name}`);
const arg = (name, fallback = null) => {
	const i = args.indexOf(`--${name}`);
	if (i === -1) return fallback;
	if (i === args.length - 1 || args[i + 1].startsWith('--')) {
		unavailable(
			`--${name} was passed with no value.`,
			`Give it one: --${name} <value>. A flag that silently falls back to its default does something other than what was asked.`,
		);
	}
	return args[i + 1];
};

// ---------------------------------------------------------------------------
// Adapter + config loading. Adapters live beside this script; providers.json
// is generated by the installer from engsys.config.yaml's providers: block.
// ---------------------------------------------------------------------------

async function loadAdapter(provider) {
	if (!/^[a-z0-9-]+$/.test(provider || '')) {
		unavailable(`provider "${provider}" is not a valid adapter name.`, 'Pass --provider codex|deepseek|grok|anthropic.');
	}
	const path = join(SCRIPT_DIR, 'workers', `${provider}.mjs`);
	if (!existsSync(path)) {
		unavailable(
			`no adapter installed for provider "${provider}" (${path}).`,
			'Enable the provider pack in engsys.config.yaml and re-run the installer.',
		);
	}
	return import(pathToFileURL(path).href);
}

function loadProviders() {
	const path = join(SCRIPT_DIR, 'providers.json');
	if (!existsSync(path)) {
		unavailable(
			'providers.json is missing beside worker-run.mjs.',
			'The installer generates it from the providers: block in engsys.config.yaml.',
		);
	}
	try {
		return JSON.parse(readFileSync(path, 'utf8'));
	} catch (e) {
		unavailable(`providers.json is unparseable: ${e.message}`, 'Re-run the installer.');
	}
}

// --check: readiness probe only. Used by `engsys verify`'s provider doctor.
if (flag('check')) {
	const provider = arg('provider');
	if (!provider) unavailable('--check requires --provider.', 'e.g. --check --provider codex');
	const adapter = await loadAdapter(provider);
	const r = adapter.check();
	console.log(`worker-run: ${provider} ${r.ready ? 'READY' : 'NOT READY'} — ${r.detail}`);
	process.exit(r.ready ? 0 : 2);
}

// ---------------------------------------------------------------------------
// Package validation. The package is the whole envelope: if it is not intact,
// nothing downstream means anything.
// ---------------------------------------------------------------------------

const packageDir = resolve(arg('package') ?? unavailable('--package is required.', 'Build one with worker-package.mjs first.'));
const manifestPath = join(packageDir, 'manifest.json');
if (!existsSync(manifestPath)) {
	unavailable(`no manifest.json in ${packageDir}.`, 'Build the package with worker-package.mjs.');
}
let manifest;
try {
	manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
} catch (e) {
	unavailable(`manifest.json is unparseable: ${e.message}`, 'Rebuild the package.');
}

const role = manifest.role;
if (!['implement', 'review', 'critique', 'investigate'].includes(role)) {
	unavailable(`manifest role "${role}" is not a known role.`, 'Rebuild the package with a valid --role.');
}
const provider = arg('provider', manifest.provider);
const worktree = resolve(manifest.worktree);
const readOnly = role !== 'implement';

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

// Per-file integrity, then the package hash the worker must echo. A package
// edited after build (a "clarified" contract, a softened constraint) would
// otherwise leave no trace of what the worker actually saw.
const fileEntries = Object.entries(manifest.files || {}).sort(([a], [b]) => (a < b ? -1 : 1));
if (!fileEntries.length) unavailable('manifest lists no files.', 'Rebuild the package.');
const hasher = createHash('sha256');
for (const [rel, expected] of fileEntries) {
	const abs = join(packageDir, rel);
	if (!existsSync(abs)) unavailable(`package file missing: ${rel}`, 'Rebuild the package.');
	const actual = sha256(readFileSync(abs));
	if (actual !== expected) {
		unavailable(
			`package file was modified after build: ${rel}`,
			'The envelope is no longer what the manifest describes. Rebuild the package.',
		);
	}
	hasher.update(rel).update('\0').update(expected).update('\n');
}
const packageHash = hasher.digest('hex');
if (packageHash !== manifest.package_hash) {
	unavailable('manifest.package_hash does not match the files it lists.', 'Rebuild the package.');
}
const hash8 = packageHash.slice(0, 8);

const issues = (manifest.issues || []).map(Number);
const contractFiles = fileEntries.map(([r]) => r).filter((r) => r.startsWith('contract/'));
if ((role === 'implement' || role === 'review') && !contractFiles.length) {
	unavailable(`a ${role} package has no contract/ files.`, 'Materialize the issue bodies — the contract is not optional.');
}

const readPkg = (rel) => readFileSync(join(packageDir, rel), 'utf8');

// A brief with no letters is the degrade-to-green shape: the run would still
// produce a verdict, but the worker was never told what to look for. `.trim()`
// is not this check — a brief of U+200B zero-width spaces sails through trim.
// Text carrying no letter in any script carries no instruction.
if (!manifest.files['brief.md'] || !/\p{L}/u.test(readPkg('brief.md'))) {
	unavailable('brief.md is missing or carries no instruction (no letters found).', 'A worker with no priors is not a worker. Rebuild the package.');
}
if ((role === 'implement' || role === 'review') && (!manifest.files['verify.md'] || !/\p{L}/u.test(readPkg('verify.md')))) {
	unavailable('verify.md is missing or empty.', 'The worker must see the gates the conductor will run. Rebuild the package.');
}

// Fix rounds: prior findings are binding, and each Critical/Warning needs an id
// the worker can ACK. "The finding did not land" stops being a vibe (§ 3.3).
let findingIds = [];
if (manifest.fix_round) {
	if (!manifest.files['prior-findings.md']) {
		unavailable('manifest says fix_round but prior-findings.md is absent.', 'Rebuild the package with --findings.');
	}
	const pf = readPkg('prior-findings.md');
	findingIds = [...pf.matchAll(/\[(F\d+)\]\s*(Critical|Warning)/g)].map((m) => m[1]);
	if (!findingIds.length) {
		unavailable(
			'prior-findings.md has no [Fn] Critical/Warning ids to acknowledge.',
			'Write findings as `- [F1] Critical file:line — …` so ACKs are checkable.',
		);
	}
}

// ---------------------------------------------------------------------------
// Provider + model resolution against the generated routing config.
// ---------------------------------------------------------------------------

const providers = loadProviders();
const pconf = (providers.workers || {})[provider];
if (!pconf || pconf.enabled === false) {
	unavailable(`provider "${provider}" is not enabled in providers.json.`, 'Enable it in engsys.config.yaml and re-install, or pick another.');
}
if (pconf.roles && !pconf.roles.includes(role)) {
	unavailable(
		`provider "${provider}" is not configured for role "${role}" (roles: ${pconf.roles.join(', ')}).`,
		'Route this role to a provider that carries it.',
	);
}
const model = arg('model', (pconf.models || {})[role] || manifest.model);
if (!model) {
	unavailable(`no model configured for ${provider}/${role}.`, 'Set providers.workers.' + provider + '.models.' + role + ' or pass --model.');
}
const effort = arg('effort', manifest.effort || 'high');
const timeoutSec = Number(manifest.timeout_sec || (providers.timeouts || {})[role] || 3600);

// ---------------------------------------------------------------------------
// Git guards — the diff must be attributable and the contract must match the
// tree, or the run cannot mean what its verdict says.
// ---------------------------------------------------------------------------

const git = (...a) => {
	try {
		return execFileSync('git', ['-C', worktree, ...a], {
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'pipe'],
		}).trim();
	} catch (err) {
		unavailable(
			`\`git ${a.join(' ')}\` failed in ${worktree}: ${(err.stderr || err.message || '').toString().trim()}`,
			'Check the package worktree.',
		);
	}
};

// `repo` must actually be the repo in the worktree. In campos27 a mistyped
// owner produced a perfectly clean review against someone else's acceptance
// criteria. And an unparseable origin must refuse rather than skip — a check
// that silently does nothing when it cannot evaluate its input is not a check.
const originUrl = git('remote', 'get-url', 'origin');
const originSlug = originUrl.replace(/\.git$/, '').match(/[:/]([^/:]+\/[^/]+)$/)?.[1];
if (!originSlug) {
	unavailable(`could not parse an owner/name pair from origin "${originUrl}".`, 'The contract cannot be confirmed to match the diff. Fix the remote.');
}
if (originSlug.toLowerCase() !== String(manifest.repo || '').toLowerCase()) {
	unavailable(
		`package repo "${manifest.repo}" is not the worktree's origin ("${originSlug}").`,
		'The contract would come from a different repository than the diff. Rebuild the package.',
	);
}

// A package built against one commit and run against another is the stale-base
// poison: a competent implementation of the wrong premise, nothing looks wrong.
const head = git('rev-parse', 'HEAD');
if (manifest.head && head !== manifest.head) {
	unavailable(
		`worktree HEAD ${head.slice(0, 7)} is not the package's head ${String(manifest.head).slice(0, 7)}.`,
		'Rebuild the package against the current tree (or reset the tree).',
	);
}

const dirtyBefore = git('status', '--porcelain', '--untracked-files=no');
if (dirtyBefore) {
	unavailable(
		`the worktree has uncommitted tracked changes:\n${dirtyBefore}`,
		role === 'implement'
			? 'Commit or stash first — otherwise the produced diff cannot be attributed.'
			: 'Commit or stash first — a review of an unfrozen tree does not describe the merge candidate.',
	);
}

/** A fingerprint of what is ACTUALLY on disk, not what the index believes.
 *  `git status` is bypassable three demonstrated ways: `update-index
 *  --assume-unchanged` makes an edited tracked file report clean; untracked
 *  files never appear; a submodule with `ignore=all` hides its own changes.
 *  `ls-files` + content hashing asks the filesystem instead. The runner's own
 *  artifacts (packages, transcripts) live under tmp/worker-package/ and are
 *  excluded by path so they never read as worker mutation. */
function treeFingerprint() {
	const tracked = git('ls-files', '-z', '--recurse-submodules').split('\0').filter(Boolean);
	const untracked = git('ls-files', '-z', '--others', '--exclude-standard').split('\0').filter(Boolean);
	const h = createHash('sha256');
	const mine = 'tmp/worker-package/';
	for (const rel of [...tracked, ...untracked].filter((r) => !r.startsWith(mine)).sort()) {
		h.update(rel).update('\0');
		try {
			h.update(readFileSync(join(worktree, rel)));
		} catch {
			h.update('<unreadable>');
		}
		h.update('\0');
	}
	return h.digest('hex');
}
const fingerprintBefore = readOnly ? treeFingerprint() : null;

// ---------------------------------------------------------------------------
// Anti-thrash: after two consecutive did-not-run results from one channel,
// stop dispatching it — change who runs the step, not the volume.
// ---------------------------------------------------------------------------

const logPath = join(worktree, 'tmp', 'worker-dispatch.log.jsonl');
if (!flag('force-provider') && existsSync(logPath)) {
	const rows = readFileSync(logPath, 'utf8')
		.split('\n')
		.filter(Boolean)
		.map((l) => {
			try { return JSON.parse(l); } catch { return null; }
		})
		.filter((r) => r && r.provider === provider && r.role === role)
		.slice(-2);
	if (rows.length === 2 && rows.every((r) => r.exit === 2)) {
		unavailable(
			`provider "${provider}" has failed to run ${role} twice in a row (see ${logPath}).`,
			'Dispatch the next provider in the chain. Override with --force-provider only after fixing the cause.',
		);
	}
}

// ---------------------------------------------------------------------------
// Invalidate output artifacts BEFORE anything else can fail. These paths are
// deterministic per package, so a re-run that dies early (bad auth, no quota)
// otherwise leaves the previous run's artifacts byte-for-byte intact — and
// whoever posts "the transcript" posts a verdict about a run that did not happen.
// ---------------------------------------------------------------------------

const transcriptPath = resolve(arg('out', join(packageDir, 'transcript.txt')));
const lastMessagePath = join(packageDir, 'last-message.txt');
for (const p of [transcriptPath, lastMessagePath]) rmSync(p, { force: true });

const adapter = await loadAdapter(provider);
const probe = adapter.check();
if (!probe.ready) {
	unavailable(`provider "${provider}" is not ready: ${probe.detail}`, 'Fix the install/auth, or dispatch the next provider in the chain.');
}

// ---------------------------------------------------------------------------
// The stdin frame — a table of contents, not the library (spec § 4). Long
// priors live on disk; the frame orders the reading and demands the footer
// last, where recency works for us instead of against us.
// ---------------------------------------------------------------------------

const stat = role === 'review' || role === 'critique' ? git('diff', '--shortstat', `${manifest.base}...HEAD`) : '';
const binding = ['contract/', 'verify.md'].concat(manifest.fix_round ? ['prior-findings.md'] : []);
const hasFocus = 'focus.md' in manifest.files;

const roleRules = {
	implement:
		'Leave your changes in the working tree. Do NOT commit, push, or open a PR — the conductor commits per issue with attribution. In your final message, list the files you changed PER ISSUE so the conductor can split the commits.',
	review:
		'You may run tests and apply mutations, but revert everything — the tree is fingerprinted and a changed tree voids your verdict. Findings need severity (Critical/Warning/Info), a file:line anchor, and a concrete failure scenario.',
	critique:
		'Read-only. Rank findings by severity. Your output informs judgment; it is not the merge gate.',
	investigate:
		'Observe first. You may run commands; no writes may survive. Report what you verified, what you refuted, and what remains unknown.',
};

const footer =
	role === 'review'
		? 'VERDICT: CLEAN   (or: VERDICT: FINDINGS)'
		: role === 'implement'
			? 'STATUS: IMPLEMENTED   (or: STATUS: REFUSED / STATUS: BLOCKED)'
			: 'STATUS: COMPLETE   (or: STATUS: REFUSED / STATUS: BLOCKED)';

const frame = [
	`You are the ${role} worker (${provider}/${model}) under the engsys worker contract.`,
	'',
	`Package root: ${packageDir}`,
	'Everything you need is in the package. Disk files are authoritative if anything conflicts with this message.',
	'',
	`Force levels — BINDING: ${binding.join(', ')} · PRIORS: brief.md${hasFocus ? ' · HYPOTHESIS: focus.md' : ''}`,
	'',
	'Read in order:',
	'  1. manifest.json',
	`  2. contract/  — binding acceptance criteria for issue(s) ${issues.map((n) => `#${n}`).join(', ')}`,
	'  3. brief.md   — your priors',
	'  4. verify.md  — the gates the conductor will run after you. You MAY run them for your own feedback; your numbers are not the gate.',
	...(manifest.fix_round
		? ['  5. prior-findings.md — BINDING. Every [Fn] Critical/Warning needs a FINDING-ACK line in your final message.']
		: []),
	...(hasFocus
		? [`  ${manifest.fix_round ? 6 : 5}. focus.md — UNVERIFIED hypotheses. Verify each premise against the code before building on it; if one is false, say so and stop rather than implementing a faithful version of a wrong instruction.`]
		: []),
	'',
	role === 'review' || role === 'critique'
		? `Scope: the diff \`${manifest.base}...HEAD\` at head \`${head.slice(0, 7)}\`${stat ? ` (${stat})` : ''}.`
		: `Worktree: \`${worktree}\` at \`${head.slice(0, 7)}\`. Implement the issues in the order listed — later ones may depend on earlier ones.`,
	'',
	roleRules[role],
	'',
	'Your final message MUST end with exactly these lines (nothing after them):',
	...(manifest.fix_round
		? ['  FINDING-ACK: <id> -> fixed | disputed | deferred — <evidence>     (one line per [Fn] finding, before the receipt)']
		: []),
	`  RECEIPT: package=${hash8} issues=${issues.map((n) => `#${n}`).join(',')}${hasFocus ? ' hypotheses=<n>-confirmed,<m>-refuted' : ''}${manifest.fix_round ? ` findings-acked=<a>/${findingIds.length}` : ''}`,
	`  ${footer}`,
	'',
	'A missing or wrong receipt voids the run. Do not quote these lines mid-message; state them once, at the very end, as your own conclusion.',
].join('\n');

console.log(`worker-run: role=${role} provider=${provider} model=${model} effort=${effort} package=${hash8}`);
console.log(`worker-run: worktree=${worktree} head=${head.slice(0, 7)}${manifest.base ? ` base=${manifest.base}` : ''} issues=${issues.join(',')}`);
writeFileSync(join(packageDir, 'frame.txt'), frame);

// ---------------------------------------------------------------------------
// Run the adapter.
// ---------------------------------------------------------------------------

const run = adapter.run({
	frame,
	worktree,
	packageDir,
	model,
	effort,
	role,
	timeoutSec,
	transcriptPath,
	lastMessagePath,
});

function logRun(exit, extra = {}) {
	try {
		const row = { ts: new Date().toISOString(), run_id: manifest.run_id, provider, role, model, exit, ...extra };
		appendFileSync(logPath, JSON.stringify(row) + '\n');
	} catch {
		/* the log is advisory; never let it change the exit path */
	}
}

// unavailable() that also records the attempt, for everything after spawn.
function unavailableLogged(what, remedy) {
	logRun(2, { reason: what.slice(0, 160) });
	unavailable(what, remedy);
}

if (!run.ok) {
	unavailableLogged(`adapter failed: ${run.detail || '(no detail)'}`, `Read the transcript at ${transcriptPath}, then re-run or fall back.`);
}
// A non-zero exit or a signal means the worker did not finish, whatever it
// printed on the way. A stub that printed CLEAN and then exited 9 — or died on
// SIGTERM/timeout — must never count.
if (run.status !== 0) {
	unavailableLogged(
		`the worker process exited ${run.status}${run.signal ? ` (signal ${run.signal})` : ''}.`,
		`Read ${transcriptPath}, then re-run or fall back.`,
	);
}

// ---------------------------------------------------------------------------
// Parse the protocol footer — from the FINAL MESSAGE only, never the
// transcript. The transcript contains the prompt echoed back, including the
// frame's own worked example of the footer; any transcript grep can be
// satisfied by a run that merely repeated its instructions.
// ---------------------------------------------------------------------------

const finalMessage = existsSync(lastMessagePath) ? readFileSync(lastMessagePath, 'utf8') : '';
const lines = finalMessage.split(/\r?\n/);
while (lines.length && lines[lines.length - 1].trim() === '') lines.pop();

const footerRe =
	role === 'review'
		? /^VERDICT:[ \t]*(CLEAN|FINDINGS)[ \t]*$/
		: /^STATUS:[ \t]*(IMPLEMENTED|COMPLETE|REFUSED|BLOCKED)[ \t]*$/;
const lastLine = lines.length ? lines[lines.length - 1] : '';
const concluded = footerRe.exec(lastLine);
if (!concluded) {
	unavailableLogged(
		`the worker did not END with the required ${role === 'review' ? 'VERDICT' : 'STATUS'} line` +
			(lastLine ? ` — its last line was: ${JSON.stringify(lastLine.slice(0, 120))}` : ' (empty final message)') +
			'.\n            A footer quoted mid-message is not a conclusion; auth expiry, quota\n' +
			'            exhaustion, idle-without-report and truncation also land here.',
		`Read ${lastMessagePath} and ${transcriptPath}, then re-run or fall back.`,
	);
}
const outcome = concluded[1];

// Ambiguity is not a pass: a CLEAN conclusion after a FINDINGS statement (or
// the reverse) means we do not know what it meant, and the safe reading of
// "I am not sure" is never "merge it".
if (role === 'review') {
	const allStated = [...new Set([...finalMessage.matchAll(/^VERDICT:[ \t]*(CLEAN|FINDINGS)[ \t]*\r?$/gm)].map((m) => m[1]))];
	if (allStated.length > 1) {
		unavailableLogged(
			`the reviewer emitted contradictory verdicts (${allStated.join(' and ')}); it ended with ${outcome}.`,
			`Read ${lastMessagePath} and adjudicate by hand, or re-run.`,
		);
	}
}

// The RECEIPT is the line immediately above the footer. It proves enumeration:
// the worker saw THIS envelope and accepted THESE issues as binding. It does
// not prove obedience — the conductor's independent gate run proves that.
const receiptLine = lines.length >= 2 ? lines[lines.length - 2] : '';
const receipt = /^RECEIPT:[ \t]*(.+)$/.exec(receiptLine);
if (!receipt) {
	unavailableLogged(
		`no RECEIPT line directly above the footer — got: ${JSON.stringify(receiptLine.slice(0, 120))}`,
		'The worker did not confirm what it read. Re-run once with a smaller package, then fall back.',
	);
}
const fields = {};
for (const m of receipt[1].matchAll(/([a-z-]+)=([^\s]+)/g)) fields[m[1]] = m[2];

if (fields.package !== hash8) {
	unavailableLogged(
		`receipt echoes package=${fields.package || '(missing)'} but this envelope is ${hash8}.`,
		'The worker did not read this package (or answered for a different run).',
	);
}
const ackedIssues = (fields.issues || '')
	.split(',')
	.map((s) => s.replace(/^#/, '').trim())
	.filter(Boolean)
	.map(Number)
	.sort((a, b) => a - b);
const wantIssues = [...issues].sort((a, b) => a - b);
if (ackedIssues.join(',') !== wantIssues.join(',')) {
	unavailableLogged(
		`receipt enumerates issues [${ackedIssues.join(',')}] but the contract is [${wantIssues.join(',')}].`,
		'The binding set was not fully acknowledged. Re-run or fall back.',
	);
}
if (hasFocus && !fields.hypotheses) {
	unavailableLogged(
		'focus.md carried hypotheses but the receipt has no hypotheses= field.',
		'The premise check was not confirmed. Re-run or fall back.',
	);
}

// Fix round: every Critical/Warning finding id needs an explicit ACK. An
// unacked finding is a finding that did not land, regardless of diff vibes.
if (manifest.fix_round) {
	const acks = new Map(
		[...finalMessage.matchAll(/^FINDING-ACK:[ \t]*(F\d+)[ \t]*(?:→|->)[ \t]*(fixed|disputed|deferred)\b.*$/gm)].map((m) => [m[1], m[2]]),
	);
	const missing = findingIds.filter((id) => !acks.has(id));
	if (missing.length) {
		unavailableLogged(
			`fix round is missing FINDING-ACK for: ${missing.join(', ')}.`,
			'Every Critical/Warning finding must be acked fixed | disputed | deferred with evidence.',
		);
	}
	const summary = [...acks.entries()].map(([id, s]) => `${id}:${s}`).join(' ');
	console.log(`worker-run: acks — ${summary}`);
}

// ---------------------------------------------------------------------------
// Post-run tree checks. Read-only roles must leave the tree byte-identical;
// implement must have changed it iff it claims to have implemented.
// ---------------------------------------------------------------------------

const headAfter = git('rev-parse', 'HEAD');
if (readOnly) {
	const fingerprintAfter = treeFingerprint();
	if (headAfter !== head || fingerprintAfter !== fingerprintBefore) {
		unavailableLogged(
			`the ${role} worker left the worktree changed — HEAD ${head.slice(0, 7)} → ${headAfter.slice(0, 7)}` +
				(fingerprintAfter !== fingerprintBefore ? ', and file contents differ' : '') +
				`\n            (its outcome was ${outcome}, and it describes a tree that is no longer here)`,
			'Reset the worktree to the frozen commit and re-run.',
		);
	}
} else {
	if (headAfter !== head) {
		unavailableLogged(
			`the implement worker moved HEAD ${head.slice(0, 7)} → ${headAfter.slice(0, 7)} — workers do not commit.`,
			'Reset to the package head, keep the tree changes if attributable, and re-run the protocol.',
		);
	}
	// The runner's own artifacts (packages, transcripts, frames) live under
	// tmp/worker-package/ and must not read as worker output — without this
	// filter a clean REFUSED run "mutated the tree" by containing its own
	// envelope, and an unchanged IMPLEMENTED run looked changed. `-uall` is
	// load-bearing: the default compacts untracked dirs to `?? tmp/`, which the
	// path filter cannot see through — per-file listing makes it exact.
	const changed = git('status', '--porcelain', '-uall')
		.split('\n')
		.filter(Boolean)
		.filter((l) => !l.slice(3).replace(/^"/, '').startsWith('tmp/worker-package/'));
	if (outcome === 'IMPLEMENTED' && !changed.length) {
		unavailableLogged(
			'STATUS: IMPLEMENTED with an unchanged tree.',
			`Nothing was produced, whatever the transcript says. Read ${transcriptPath}.`,
		);
	}
	if ((outcome === 'REFUSED' || outcome === 'BLOCKED') && changed.length) {
		unavailableLogged(
			`STATUS: ${outcome} but the tree was mutated (${changed.length} path(s)) — the state is unattributable.`,
			'Reset the worktree; read the final message for the refusal evidence.',
		);
	}
	if (changed.length) {
		console.log(`worker-run: tree changes (uncommitted, conductor commits per issue):`);
		for (const c of changed.slice(0, 40)) console.log(`  ${c}`);
		if (changed.length > 40) console.log(`  … and ${changed.length - 40} more`);
	}
}

// ---------------------------------------------------------------------------
// Verdict → exit. 0 only for an unambiguous positive on an intact protocol.
// ---------------------------------------------------------------------------

const tokens = run.tokens ?? null;
const positive = outcome === 'CLEAN' || outcome === 'IMPLEMENTED' || outcome === 'COMPLETE';
const exit = positive ? 0 : 1;
logRun(exit, { outcome, tokens });

console.log(`\nworker-run: ${role === 'review' ? 'VERDICT' : 'STATUS'}: ${outcome}${tokens ? `  (tokens=${tokens})` : ''}`);
console.log(`worker-run: receipt   → package=${hash8} issues=${wantIssues.map((n) => `#${n}`).join(',')}${fields.hypotheses ? ` hypotheses=${fields.hypotheses}` : ''}`);
console.log(`worker-run: final msg → ${lastMessagePath}`);
console.log(`worker-run: transcript → ${transcriptPath}`);
if (role === 'implement' && exit === 0) {
	console.log('\nworker-run: NOT verified. Run verify.md yourself, commit per issue with a');
	console.log(`worker-run: \`Worker: ${provider}/${model}\` trailer, then review on ANOTHER family.`);
}
process.exit(exit);
